---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mangonetcom/public_html/fieldpulse
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
